// Package provider defines the interface for sandbox backend providers.
// This abstraction allows switching between different backends (Firecracker, FC Session, etc.)
// without modifying the API layer.
package provider

import (
	"context"
	"errors"
	"time"
)

// Error definitions
var (
	// ErrSandboxNotFound is returned when a sandbox is not found
	ErrSandboxNotFound = errors.New("sandbox not found")

	// ErrSandboxAlreadyExists is returned when trying to create a sandbox that already exists
	ErrSandboxAlreadyExists = errors.New("sandbox already exists")

	// ErrInvalidTemplate is returned when the template doesn't exist
	ErrInvalidTemplate = errors.New("invalid template")

	// ErrProviderUnavailable is returned when the provider is temporarily unavailable
	ErrProviderUnavailable = errors.New("provider unavailable")
)

// SandboxConfig contains the configuration for creating a new sandbox.
type SandboxConfig struct {
	// TemplateID is the name of the template (FC function name)
	TemplateID string

	// Timeout is the maximum duration the sandbox can run
	Timeout time.Duration

	// Metadata is user-provided metadata for the sandbox
	Metadata map[string]string

	// EnvVars are environment variables for the sandbox
	EnvVars map[string]string
}

// SandboxInfo contains information about a sandbox.
type SandboxInfo struct {
	// SandboxID is the unique identifier (same as FC Session ID)
	SandboxID string

	// TemplateID is the template (function) name
	TemplateID string

	// State is the current state of the sandbox
	State SandboxState

	// CreatedAt is when the sandbox was created
	CreatedAt time.Time

	// ExpiresAt is when the sandbox will expire
	ExpiresAt time.Time

	// Metadata is user-provided metadata
	Metadata map[string]string
}

// SandboxState represents the state of a sandbox.
type SandboxState string

const (
	SandboxStateRunning SandboxState = "running"
	SandboxStateIdle    SandboxState = "idle"
	SandboxStateExpired SandboxState = "expired"
	SandboxStateDeleted SandboxState = "deleted"
)

// ConnectionInfo contains the information needed to connect to a sandbox's envd.
type ConnectionInfo struct {
	// Endpoint is the FC session endpoint URL
	Endpoint string

	// AccessToken is the token for authenticating with envd
	AccessToken string

	// SessionID is the session ID for affinity headers
	SessionID string
}

// ListFilter contains filters for listing sandboxes.
type ListFilter struct {
	// TemplateID filters by template (optional)
	TemplateID string

	// Limit is the maximum number of results
	Limit int32

	// NextToken is the pagination token
	NextToken string
}

// ListResult contains the result of listing sandboxes.
type ListResult struct {
	// Sandboxes is the list of sandbox info
	Sandboxes []*SandboxInfo

	// NextToken is the token for the next page (empty if no more pages)
	NextToken string
}

// CommandResult contains the result of a command execution.
type CommandResult struct {
	// ExitCode is the exit code of the process
	ExitCode int32

	// Stdout is the standard output of the process
	Stdout string

	// Stderr is the standard error of the process
	Stderr string
}

// CommandConfig contains the configuration for running a command.
type CommandConfig struct {
	// Command is the command to execute
	Command string

	// Args are the command arguments
	Args []string

	// EnvVars are environment variables for the command
	EnvVars map[string]string

	// Cwd is the working directory
	Cwd string

	// Timeout is the command timeout
	Timeout time.Duration
}

// SandboxProvider is the interface for sandbox backend providers.
// It abstracts the underlying infrastructure (Firecracker, FC Session, etc.)
type SandboxProvider interface {
	// Create creates a new sandbox and returns its info.
	// The sandbox ID is generated by the provider (Session ID = Sandbox ID).
	Create(ctx context.Context, config *SandboxConfig) (*SandboxInfo, error)

	// Get returns information about a sandbox by ID.
	// Returns ErrSandboxNotFound if the sandbox doesn't exist.
	Get(ctx context.Context, sandboxID string) (*SandboxInfo, error)

	// Delete deletes a sandbox by ID.
	// Returns ErrSandboxNotFound if the sandbox doesn't exist.
	Delete(ctx context.Context, sandboxID string) error

	// List returns a paginated list of sandboxes.
	List(ctx context.Context, filter *ListFilter) (*ListResult, error)

	// Connect returns connection information for accessing a sandbox's envd.
	// Returns ErrSandboxNotFound if the sandbox doesn't exist.
	Connect(ctx context.Context, sandboxID string) (*ConnectionInfo, error)

	// RunCommand executes a command in the sandbox and returns the result.
	// Returns ErrSandboxNotFound if the sandbox doesn't exist.
	RunCommand(ctx context.Context, sandboxID string, config *CommandConfig) (*CommandResult, error)
}
